### ISSUE TITLE
Feature request: dc.js-like crosschart filtering

### ISSUE THREAD

**Issue by fpmcardoso** [rstudio/crosstalk#12]
Hi there! Crosstalk is an awesome package and I'm very interested in its development.
If possible, I'd like to know if there are any plans to have the plots work with one another such as in the DCR package:
https://github.com/massmutual/dcr

Thank you.

**Comment by timelyportfolio** [comment]
very interesting and thanks for the link.  Here is a quick experiment I did with dc.js and crosstalk http://bl.ocks.org/timelyportfolio/fff10346123c40db25cdc9e40b52dd5d.

**Comment by jcheng5** [comment]
I took a close look at crossfilter and dc.js and concluded they're too advanced/opinionated to integrate with crosstalk. The filtering logic is quite different because each plot is both filter input and filter output; a plot needs to know what rows are 1) part of its own filter, 2) outside of its own filter, 3) filtered out by everyone else. This is complicated to implement for widgets that aren't designed for it, and also doesn't play well with linked brushing (I haven't seen any dc.js examples that combine linked brushing and filtering).

@timelyportfolio's experiment is cool but it's not doing filtering at all, just linked brushing.

**Comment by jcheng5** [comment]
Forgot to add: I do think crossfilter/dc.js deserve a place in the R universe, but crosstalk is aiming for lowest-common-denominator type of interactivity and crossfilter deserves to be its own thing that plays to its strengths.
