### ISSUE TITLE
Crosstalk with leaflet on Windows - basemap will not draw in Chrome/Firefox/IE

### ISSUE THREAD

**Issue by libjohn** [rstudio/crosstalk#30]
I'm reporting this to crosstalk.  Not sure if it should be cross-reported in leaflet.

While exploring flexdashboards I discovered this problem when starting to use crosstalk with DT, leaflet and via crosstalk.  When I compiled the rmarkdown, the resulting leaflet map will not draw with a basemap -- when opening the resulting html in a standard web browser.  

I want to note, the base map drew fine in the Rstudio's web browser.  But, also, when trying to open the resulting knitted html page in a standard browser, the map did have accurately geolocated points -- just no basemap.  All the while the web browser kept churning until it timed out.

I've reproduced this error on 4 different Windows workstations.  But, I cannot reproduce the problem using R/Rstudio on a Linux docker container.  

The other problem, after it arose, I could no longer create any leaflet maps, regardless of flexdashboards, DT, or crosstalk.  To fix this problem I eventually installed the original leaflet version.

I tried several different versions of leaflet (1.1.1 and 1.1.0.90000) until going back to version 1.0.1.  At that point (1.0.1) I can create leaflet maps again and they work in standard browsers.  

I still cannot generate crosstalks that work with DT and leaflet -- again, unless on a linux-based R.

The procedures I followed to get my leaflet working again are here - https://github.com/libjohn/crosstalk-leaflet-error/tree/master#crosstalk-leaflet-error.  Files that reproduce the problem are in the same repo.

**Comment by jcheng5** [comment]
I just fixed this bug this morning. If you install leaflet from GitHub the basemap problem should be gone. Sorry about that.

If you don't have the option of running the GitHub version of leaflet, you can use the latest CRAN version but instead of calling `addTiles()`, call:

```
leaflet() %>%
  addTiles("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    attribution = paste("&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a>",
      "contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA</a>")
  )
```

The problem was that the default URL is like the above but without the leading `"https:"`. This instructs the browser to use whatever scheme, http or https, the current page is loaded with. Unfortunately we didn't think about the `file` scheme, which is what is used when you open an .html file from the hard drive. Hardcoding the scheme to https fixes the problem.
