### ISSUE TITLE
Make a selection box appearing only on double click

### ISSUE THREAD

**Issue by pythiantech** [rstudio/crosstalk#58]
While running a shiny application, the 'make a selection' box does not appear until you double click on the icon. Thereafter if you resize it, it disappears again. I have tried this in both Firefox and Chrome.

Here's the code I am using:
```
library(crosstalk)
library(leaflet)
library(DT)
library(shiny)

ui <- fluidPage(
  fluidRow(
    column(6, leafletOutput('cmap',height=600, width='100%')),
    column(6, dataTableOutput('cmapTable'))
  )
)

server <- function(input, output, session) {
  sDraft <- SharedData$new(df)

  output$cmap <- renderLeaflet({
    leaflet(sDraft) %>% addTiles() %>%
      addMarkers(lng = ~lon, lat=~lat)
    })

  output$cmapTable <- renderDataTable({
    datatable(sDraft, options = list(scrollX = TRUE),filter='top')
  },server = FALSE)
}

shinyApp(ui, server)
```
Here's the `df` data:

```
structure(list(mmsi = c(538004533L, 538004534L, 538004536L, 538005117L, 
538005118L, 538005120L), Name = c("STI GARNET", "STI TOPAZ", 
"STI ONYX", "STI LE ROCHER", "STI FONTVIEILLE", "STI VILLE"), 
    Dwt = c(51840L, 51840L, 49990L, 49990L, 49990L, 49990L), 
    lat = c(25.0050144, 11.213192, 1.26014328, 13.41435, 32.3204, 
    5.7550416), lon = c(55.05124, 121.773193, 103.914574, -18.28864, 
    -117.113571, 81.47743)), row.names = c(NA, -6L), class = c("grouped_df", 
"tbl_df", "tbl", "data.frame"), vars = "mmsi", drop = TRUE, indices = list(
    0L, 1L, 2L, 3L, 4L, 5L), group_sizes = c(1L, 1L, 1L, 1L, 
1L, 1L), biggest_group_size = 1L, labels = structure(list(mmsi = c(538004533L, 
538004534L, 538004536L, 538005117L, 538005118L, 538005120L)), row.names = c(NA, 
-6L), class = "data.frame", vars = "mmsi", drop = TRUE))
```
I am on a MacBook Pro (macOS High Sierra Version 10.13.6)

**Comment by jcheng5** [comment]
@schloerke, do you mind investigating? Seems likely to be in leaflet?

**Comment by schloerke** [comment]
The leaflet map when it is made without shiny works as expected.  

With shiny, the map is being redrawn multiple times.  When you "click" and it selects data for the first time, it glitches as if it was reset is when the map is being redrawn.  This glitch only happens when something within the data is being set.  (The second click would not select __new__ data, so it would work as expected.)

I believe the shared data is not being set properly (and causing a trigger to draw the map), as shinyreactlog is trying to depend on some shared data node that doesn't exist.


Somewhere in these set of commits: https://github.com/schloerke/shiny/compare/barret/reactlog...schloerke:barret-reactlog-merge?expand=1 is a change that is causing the issue.  (barret/reactlog works as expected, barret-reactlog-merge contains the latest master from shiny)

The reactlog graph looks like:
![screen shot 2018-09-05 at 10 54 27 am](https://user-images.githubusercontent.com/93231/45101724-2db5c580-b0fa-11e8-9f42-a4976ed831f5.png)
The bottom observe ... https://github.com/rstudio/crosstalk/blob/1c67fbfaf742234790b50e146f3a348f0fed53dc/R/crosstalk.R#L249-L256 ... is changing the upper left input value with no dependency or isolation relationship. (WEIRD!)

The reactlog graph on a _working as expected_ branch (schloerke/shiny - barret/reactlog) looks like:
![screen shot 2018-09-05 at 10 54 45 am](https://user-images.githubusercontent.com/93231/45101879-71103400-b0fa-11e8-9824-166a857f6041.png)

**Comment by pythiantech** [comment]
@schloerke @jcheng5 Thanks, working fine now!
