### ISSUE TITLE
Vulnerability with jquery & bootstrap

### ISSUE THREAD

**Issue by stepintooracledba** [rstudio/crosstalk#73]
Hi Team,

crosstalk package still uses older version of jquery and bootstrap. Can we have the latest version updated?

**Comment by jcheng5** [comment]
For jquery, this can happen soon, once Shiny v1.4 hits CRAN (next few weeks).

Bootstrap will be quite a bit further in the future due to major compatibility breakage between bootstrap 3 and 4; this will need to be resolved not just in crosstalk but in the entire htmlwidgets/shiny/rmarkdown ecosystem. However, we are actively working on the problem.

**Comment by maelle** [comment]
I've just run code from https://github.com/sonatype-nexus-community/oysteR and got https://ossindex.sonatype.org/vuln/49da4413-af2b-4e55-acc0-9c752e30dde4

**Comment by PathosEthosLogos** [comment]
#53 duplicate
This thread should be closed

**Comment by cpsievert** [comment]
Yep, thanks!
